version: "3"

# This is the conversion from a script to a dockerized version of the script
services:

  stubs_python_envoy_service_cluter:
    image: grpc/python
    command:
      - python
      - -m
      - grpc.tools.protoc
      - --python_out=/stubs
      - --grpc_python_out=/stubs
      - -I/protos/1
      - -I/protos/2
      - -I/protos/3
      - -I/protos/4
      - -I/protos/5
      - /protos/1/envoy/service/accesslog/v2/als.proto
      - /protos/1/envoy/service/accesslog/v3/als.proto
      - /protos/1/envoy/service/auth/v2/attribute_context.proto
      - /protos/1/envoy/service/auth/v2/external_auth.proto
      - /protos/1/envoy/service/auth/v3/attribute_context.proto
      - /protos/1/envoy/service/auth/v3/external_auth.proto
      - /protos/1/envoy/service/cluster/v3/cds.proto
      - /protos/1/envoy/service/discovery/v2/ads.proto
      - /protos/1/envoy/service/discovery/v2/hds.proto
      - /protos/1/envoy/service/discovery/v2/rtds.proto
      - /protos/1/envoy/service/discovery/v2/sds.proto
      - /protos/1/envoy/service/discovery/v3/ads.proto
      - /protos/1/envoy/service/discovery/v3/discovery.proto
      - /protos/1/envoy/service/endpoint/v3/eds.proto
      - /protos/1/envoy/service/health/v3/hds.proto
      - /protos/1/envoy/service/listener/v3/lds.proto
      - /protos/1/envoy/service/load_stats/v2/lrs.proto
      - /protos/1/envoy/service/load_stats/v3/lrs.proto
      # Requires io.prometheus.client.MetricFamily
      #- /protos/1/envoy/service/metrics/v2/metrics_service.proto
      #- /protos/1/envoy/service/metrics/v3/metrics_service.proto
      - /protos/1/envoy/service/ratelimit/v2/rls.proto
      - /protos/1/envoy/service/ratelimit/v3/rls.proto
      - /protos/1/envoy/service/route/v3/rds.proto
      - /protos/1/envoy/service/route/v3/srds.proto
      - /protos/1/envoy/service/runtime/v3/rtds.proto
      - /protos/1/envoy/service/secret/v3/sds.proto
      - /protos/1/envoy/service/tap/v3/tap.proto
      - /protos/1/envoy/service/tap/v3/tapds.proto
      # Has extra "ruby_package" option in the opencensus tree that generates an error.
      #- /protos/1/envoy/service/trace/v2/trace_service.proto
      #- /protos/1/envoy/service/trace/v3/trace_service.proto

      # Required on imports
      - /protos/1/envoy/annotations/resource.proto
      - /protos/1/envoy/api/v2/core/address.proto
      - /protos/1/envoy/api/v2/core/base.proto
      - /protos/1/envoy/api/v2/core/health_check.proto
      - /protos/1/envoy/api/v2/discovery.proto
      - /protos/1/envoy/api/v2/endpoint/endpoint_components.proto
      - /protos/1/envoy/api/v2/endpoint/load_report.proto
      - /protos/1/envoy/api/v2/ratelimit/ratelimit.proto
      - /protos/1/envoy/config/core/v3/address.proto
      - /protos/1/envoy/config/core/v3/base.proto
      - /protos/1/envoy/config/core/v3/health_check.proto
      - /protos/1/envoy/config/endpoint/v3/endpoint_components.proto
      - /protos/1/envoy/config/endpoint/v3/load_report.proto
      - /protos/1/envoy/config/tap/v3/common.proto
      - /protos/1/envoy/data/accesslog/v2/accesslog.proto
      - /protos/1/envoy/data/accesslog/v3/accesslog.proto
      - /protos/1/envoy/data/tap/v3/wrapper.proto
      - /protos/1/envoy/extensions/common/ratelimit/v3/ratelimit.proto
      - /protos/1/envoy/type/http_status.proto
      - /protos/1/envoy/type/v3/http_status.proto
      - /protos/2/udpa/annotations/migrate.proto
      - /protos/2/udpa/annotations/versioning.proto
      - /protos/3/validate/validate.proto
      - /protos/4/google/api/annotations.proto
      - /protos/4/google/api/http.proto
      - /protos/4/google/rpc/status.proto

    volumes:
      - ./.tmp/data-plane-api:/protos/1
      - ./.tmp/udpa:/protos/2
      - ./.tmp/protoc-gen-validate:/protos/3
      - ./.tmp/googleapis:/protos/4
      - ./.tmp/opencensus-proto/src:/protos/5
      - ./out:/stubs
